### PR TITLE
Add support for custom inspect uri format for Blazor

### PR DESCRIPTION
**Pull request by digeff**
Add support for custom inspect uri format for Blazor

See https://github.com/microsoft/vscode-js-debug/issues/302 for more details

Added some extra logging that I used while debugging this feature

cc @connor4312 @SteveSandersonMS @roblourens

### CODE REVIEW

**Comment by connor4312** [comment]
Changes look good to me. Could we get an integration test here? Could be something super synthetic like standing up a `ws` server in the test, passing a config like

```
inspectUri: `ws://127.0.0.1:${testServer.port}?port={url.port}&...
```

and then just waiting for any connection and checking the query params.

**Comment by digeff** [comment]
Can we merge this change in now so it's easier for people to start testing it, and I'll work on the integration tests meanwhile?

**Comment by roblourens** [comment]
Would also just like a basic unit test of the parsing logic in `constructInspectorWSUri`. I can merge it now though.

**Comment by EricCornelson** [comment]
Should we also add usage notes in the package.json? Or is this meant to be a "hidden" launch parameter?

**Comment by roblourens** [comment]
Oh, they will get a warning if it isn't registered in the package.json, which we probably don't want.

**Comment by SteveSandersonMS** [comment]
@digeff @connor4312 How does one signal that the browserInspectUri needs to be uri-component encoded when being inserted into the query string part of a URL?

**Comment by SteveSandersonMS** [comment]
Maybe there should be a {browserInspectUriEncoded} parameter to use for this.

**Comment by connor4312** [comment]
An `{browserInspectUriEncoded}` parameter would work for me.

**Pull request merged**
