### PR TITLE
potential fix for #624

### PR DESCRIPTION
**Pull request by connor4312**
Fixes https://github.com/microsoft/vscode-js-debug/issues/624

@DavidShoe please give this a shot, I'm not as familiar with webview scenarios as you are. [Vsix package here](https://memes.peet.io/img/js-debug-nightly-624.vsix)

### CODE REVIEW

**Comment by connor4312** [comment]
@DavidShoe let me know if you still see an issue with this build. If not, I'll get it merged and close the issue. Thanks!

**Comment by DavidShoe** [comment]
I used the strings:  "urlFilter": "*index.html?i=1" and "urlFilter": "about:blank",

The about:blank was working previously but no longer does.  And the other string still isn't working.  Both these strings work with the old adapter.

**Comment by connor4312** [comment]
Are you able to provide a sample .exe where I can see the issue you're describing? This worked in the cases I tested using the sample webview that Jon provided: https://memes.peet.io/img/20-08-69c42042-362f-42e5-acdd-c571ab4bc754.webm

**Comment by connor4312** [comment]
Verified over a call

**Pull request merged**
