### PR TITLE
corrected hostname assignment

### PR DESCRIPTION
**Pull request by rajinder-yadav**
When family is IPv6 hostname should be ::1

### CODE REVIEW

**Comment by connor4312** [comment]
This is incorrect. The purpose of this code is to try the other loopback from the one that's currently being requested.

**Comment by rajinder-yadav** [comment]
So you're checking if the system is using ipv6 and then using ip4.

On my system ip4 is broken, but ipv6 work.

So before the code had "parsed.hostname = '127.0.0.1' hard coded, and now you check for ipv6 usage and still set the hostname to "127.0.0.1", this logic doesn't make any sense.

```sh
$ curl -I http://127.0.0.1:4200/vendor.js.map
curl: (7) Failed to connect to 127.0.0.1 port 4200 after 0 ms: Couldn't connect to serve
```

```sh
$ curl -I http://\[::1\]:4200/vendor.js.map
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Accept-Ranges: bytes
Content-Length: 3025276
ETag: W/"2e297c-uigHuL6i7krMsHv4WkzAwCZEuEk"
Date: Sun, 11 Dec 2022 09:52:21 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

**Comment by rajinder-yadav** [comment]
```js
import { LookupAddress, promises as dns } from 'dns';

async function doDNSLookup() {
  let resolved: LookupAddress;
  try {
    resolved = await dns.lookup('localhost');
    console.log(resolved);
  } catch {
    console.log('error');
  }
}

doDNSLookup();
```

Output

```sh
{ address: '::1', family: 6 }
```

**Comment by connor4312** [comment]
Please see the context of where this is used; it's only hit as a fallback in case the initial request fails in order to try the other host. Actually the bug is there, looks like a typo in `localhost`

**Comment by rajinder-yadav** [comment]
Thanks @connor4312, I realized what the fallback code was doing after more refelction :)
I did look at CONTRIBUTIONS.md and trying to get a setup going locally but I get tons of error with "npm install"

```sh
$ cd vscode-js-debug/
$ npm i

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: gulp-tsb@4.0.6
npm ERR! Found: typescript@4.6.3
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^4.6.3" from the root project
npm ERR!   peer typescript@">=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta" from tsutils@3.21.0
npm ERR!   node_modules/@typescript-eslint/eslint-plugin/node_modules/tsutils
npm ERR!     tsutils@"^3.21.0" from @typescript-eslint/eslint-plugin@5.17.0
npm ERR!     node_modules/@typescript-eslint/eslint-plugin
npm ERR!       dev @typescript-eslint/eslint-plugin@"^5.17.0" from the root project
npm ERR!   4 more (tsutils, tsutils, ts-node, vscode-nls-dev)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"^3.0.0" from gulp-tsb@4.0.6
npm ERR! node_modules/gulp-tsb
npm ERR!   dev gulp-tsb@"^4.0.6" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typescript@3.9.10
npm ERR! node_modules/typescript
npm ERR!   peer typescript@"^3.0.0" from gulp-tsb@4.0.6
npm ERR!   node_modules/gulp-tsb
npm ERR!     dev gulp-tsb@"^4.0.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/yadav/.npm/_logs/2022-12-23T02_17_14_107Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yadav/.npm/_logs/2022-12-23T02_17_14_107Z-debug-0.log
```

**Comment by connor4312** [comment]
Ah, you'll have to `npm install --legacy-peer-deps`. We have an old unhappy dependency...

**Comment by rajinder-yadav** [comment]
Hello @connor4312, a few questions from CONTRIBUTING.md

Step 3: Run the `Extension` launch configuration.

How do I do this? 

After "npm run watch", how do I use this exension to test my code changes?
Do I just open a new vscode with the nightly debug extension installed and it will pick up this local build in watch mode?

**Comment by connor4312** [comment]
You can run this from the Debug view, or in the command palette (Ctrl/Cmd+P) type `debug ext` and you should find it. Running that will automatically open a new instance of VS Code.

You _will_ want to be using the nightly version of the extension, since `npm run watch` generates a nightly build that is 'replaced' in the window when you debug it.

**Comment by rajinder-yadav** [comment]
Thanks got the debug setup working.

**Pull request closed without merging**
