### PR TITLE
Only get root level scripts property for codelens

### LINKED ISSUE #350: Package.json Codelens gets confused with nested scripts attribute
If you have a package.json which contains another "scripts" attribute, nested in another section, it will take precedence over the actual  scripts part.
```json
{
  "name": "demo",
  "version": "0.0.1",
  "files": [],
  "scripts": {
    "test": "echo test"
  },
  "sub": {
    |> Debug
    "scripts": {}
  }
}
```

### PR DESCRIPTION
**Pull request by SantoJambit**
Resolves #350

### CODE REVIEW

**Comment by SantoJambit** [comment]
Currently looking into how to unit test this.

**Comment by SantoJambit** [comment]
Took me a while longer to create the tests, but I think it's good to go now.

**Comment by connor4312** [comment]
Thanks for the contribution, and the unit tests!

**Comment by SantoJambit** [comment]
thanks for the quick response :)

**Pull request merged**
