### PR TITLE
fix: wait for targets before returning from disconnect

### LINKED ISSUE #165: Debug adapter still sending events after sending the response to "disconnect"
We've noticed the adapter sending the following events after responding to the "disconnect" request:

- loadedSource
- thread
- process
- output
- terminated

(after which, VS expects the session to be completed). These events are unexpected on the VS side, and cause assertion errors:

image
processEventAssert
image

logs attached
[vscode-debugadapter(1).log](https://github.com/microsoft/vscode-js-debug/files/3946518/vscode-debugadapter.1.log)
[vscode-debugadapter.log](https://github.com/microsoft/vscode-js-debug/files/3946522/vscode-debugadapter.log)

### PR DESCRIPTION
**Pull request by connor4312**
Also reworks the terminal process launcher to verify the process is
killed before returning.

Probably fixes #165

### CODE REVIEW

**Comment by EricCornelson** [comment]
Giving this a test run now

**Comment by EricCornelson** [comment]
Still getting thread events after the disconnect response

image


Logs:
[vscode-debugadapter.log](https://github.com/microsoft/vscode-js-debug/files/4094343/vscode-debugadapter.log)

**Comment by connor4312** [comment]
Thanks! Were you seeing this mostly in Chrome or does it also (continue?) happening on Node.js?

**Comment by EricCornelson** [comment]
Only ever tested on Chrome so far

**Comment by connor4312** [comment]
Okay, thanks, I'll look into that more.

**Comment by connor4312** [comment]
I'd like to merge this PR as I think the Node stuff is a good bit better, but I won't close the original issue yet.

**Pull request merged**
